### ISSUE TITLE
NewWriterBufferSize won't buffer with io.Copy

### ISSUE THREAD

**Issue by KromDaniel** [gobwas/ws#106]
Hey,
I was encountered with the following situation:

Creating a writer

```go
w := wsutil.NewWriterBufferSize(conn, ws.StateServerSide, ws.OpText, someLengthConstant)
```

With the following code:

```go
// len(payload) > someLengthConstant
io.Copy(w, bytes.NewReader(payload)) // ignore error handling for example
...
w.Flush()
```
won't transfer the data buffered, instead the entire payload is transferred with a single frame.

When using direct

```go
 w.ReadFrom(bytes.NewReader(payload))
```

The data is indeed chunked as expected

`io.Copy` check first is reader implement `io.WriterTo interface.` but it should still work, isn't it?

if it's by design, could maybe add a word about it in the docs, was figuring it out with tcpdump / wirshark 

Thanks!

**Comment by gobwas** [comment]
Hi @KromDaniel, sorry for a huge delay on replying to it. 
I think that's because bytes.Reader passes it's payload as is in case of `io.WriterTo` call. `wsutil.Writer` has the similar behaviour to `bufio.Writer` in cases, when internal buffer is empty, and given payload to write is larger than it. In case of `w.ReadFrom()` we are using `wsutil.Writer`'s internal buffer for each `r.Read(buf)` call, so message get chunked.

Please, feel free to add any clarification of such behaviour in docs -- I would glad to merge them! 👍

**Comment by KromDaniel** [comment]
@gobwas better late than never :P 
Thank for the explanation, always great to learn new stuff. I'll see if I can improve the docs and open PR!

**Comment by gobwas** [comment]
@KromDaniel great! Thank you!
