### ISSUE TITLE
Question: how/where to save URI parsed during Upgrader.Upgrade() ?

### ISSUE THREAD

**Issue by JordanP** [gobwas/ws#14]
Hi,
Thanks for your blog post and this nice library. 

I am considering using it for my own websocket-based application. My app is very similar to your chat server example in your `ws-examples` repo. One difference though, the user name is supplied by the end user in the URI, during initial connection (websocket upgrade) whilst in your chat server, the user name is a random one generated server side (see `randName` function).

What I would like is somehow to save in a variable the URI of the HTTP GET request used to upgrade to WS. That variable should be accessible in my app logic, that is outside of the `Upgrader.Upgrade`. 

The signature of `Upgrader.Upgrade` is `Upgrade(conn io.ReadWriter) (hs Handshake, err error)`. I see 2 possibilities to do what I'd like.

1. Add a new parameter to Upgrade, something like `Upgrade(conn io.ReadWriter, conn_storage map[string]interface{})` and put the info (URI, HTTP Headers etc.) I want to save in that new map 
2. Change the `Handshake` type and add a new field (in addition to Protocol and Extensions) that would also store the URI at which the handshake was done.

All in all, it boils down to saving the result of some internal parsing already done by the nice `upgrade()` method.

I believe this feature request could be beneficial to others, so maybe we can come up with something flexible enough? What do you think ? 

Thanks

**Comment by gobwas** [comment]
Hi @JordanP,

Thank you for your feedback on article =)

So, there are few ways you could save the GET parameters from URI. It depends on the performance requirements to your application. If the memory consumption is not the main problem, then you can use `net/http` server and `ws.UpgradeHTTP()` function, instead of `ws.Upgrade()`:

```go
http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
    conn, brw, hs, err := ws.UpgradeHTTP(r, w, nil)
    if err != nil {
        // handle err
    }
    // save r.URL.Query()["user-name"]
})
``` 

Note that `ws.Upgrade` provides way to use so-called **zero-copy** upgrade. It does not allocates any data to fill structs like `http.Request` and so on. It is useful for high-load applications, which are required to be as much efficient as possible. There is [`ws.Upgrader`](https://godoc.org/github.com/gobwas/ws#Upgrader) struct (which default instance is used by `ws.Upgrade`) which allows to copy any data by your self:

```go
var userName string
hs, err := (ws.Upgrader{
    OnRequest: func(host, uri []byte) (err error, code int) {
        // Parse query from uri somehow. 
        // For example (not most efficient), with use of net/url.ParseQuery().
        // Store the appropriate value to the userName variable.
        // If some error occur, return it and corresponding HTTP status code.
        return nil, 0
    },
}).Upgrade(conn)
```

That is, `ws.Upgrader` is used to avoid allocations that will not be used by a particular app. Filling some structs inside in generic way will cancel the idea of zero-copy. That's why there are callbacks in `ws.Upgrader` for: to give you ability to implement your own logic of copying data without redundancy.

Cheers =)

**Comment by JordanP** [comment]
Thanks for your detailed answer. Memory requirement is a bit of an issue to me, my app is currently handling around 700k concurrent WS session (with gorilla/websocket), not the 3M you have at mail.ru but still :) 

I like the second example, I am kinda new to Go, but I understand that the function passed to `OnRequest` would be a closure given that it uses/captures the `userName` variable defined in the outer scope. In this example, would a new `Upgrader` struct by initialized for each and every new WS session ? Once compiled, is this efficient, i.e could the compiler do some speed magic ?

**Comment by gobwas** [comment]
Yes, 700K is a huge amount =)
Yes, `Upgrader` will be initialized for every accept operation, but struct itself will be allocated on stack, thus such initialization will cheap. The captured variables will escape to heap, but it is seems ok when you want store copied data outside the accept operation function.
