### ISSUE TITLE
Network Send Overhead

### ISSUE THREAD

**Issue by pascaldekloe** [gobwas/ws#62]
The API calls for a separate write for the header. This results in either an extra TCP package (with a few bytes) or (Nagle) overhead.

**Comment by pascaldekloe** [comment]
I've made a competing implementation which includes a TCP benchmark <https://github.com/pascaldekloe/websocket#performance-on-a-mac-pro-late-2013>. It would be interesting to compare the two.

**Comment by gobwas** [comment]
Hello there,

If you want to use this library and not to have network overhead, you should use `bufio.Writer` to write frames and `bufio.Reader` to read them. This separation of concern is by design.

Sergey.

**Comment by pascaldekloe** [comment]
Using `bufio` as proposed would cause 4 memory allocations and is not high-performant at all. Plus you need to flush the writers or risk pending frames.

This issue is *not* closed at all. How about me starting with a useful benchmark setup @gobwas?

**Comment by gobwas** [comment]
Which 4 memory allocations you are talking about? With proper reuse there is a single allocation per writer for its inner buffer. And yes, of course you always need to flush in memory buffer to the wire.

If you are interested in details of such optimizations in real world at mail.ru you could read [this article](https://medium.freecodecamp.org/million-websockets-and-go-cc58418460bb).

**Comment by pascaldekloe** [comment]
> Which 4 memory allocations you are talking about?

One for each reader and one for each buffer.

I am doing such optimizations in real world and I did read the article. The article provides no code, no measurments [benchmarks] so we'll have to take his word for it. He most certainly won't use buffered I/O with a million connections.

As you can see in my benchmark is that TCP takes the highest cost thus it kind of makes sense to limit I/O. This project only provides micro-benchmarks and leave out the overall picture. I'm offering help here to get representative numbers.

**Comment by cristaloleg** [comment]
@pascaldekloe can you share your benchmark, please?

**Comment by gobwas** [comment]
Do you mean allocation for particular structure holding buffer `[]byte`?

So, if you optimizing such things (it looks to me little bit unusual, I will explain below why), and you want to stick on the smallest possible frame payloads (such as 125 bytes from your example, which is also very weird idea for general purpose library) and get rid of those two buffer allocations, you of course could implement custom buffered reader/writer (as you practically did inside your example), and do something like this:

```
package constbufio

const ReaderSize = 131

type Reader struct {
	Src io.Reader
	buf [ReaderSize]byte
	has int
}

func (r *Reader) Read(p []byte) (int, error) {
	if r.has >= len(p) {
		// copy bytes
	} else {
		// read from src
		// but if we read more than len(r.buf), we could return an error or prepare realloc.
	}
	return 0, nil
}
```

And then inside the app:

```
package app

import "ws"

type Conn struct {
	constbufio.Reader
}

func NewConn(conn io.ReadWriter) *Conn {
	c := new(Conn)
	c.Reader.Src = conn
	return c
}

func (c *Conn) ReadFrame() (ws.Frame, error) {
	return ws.ReadFrame(c)
}
```

With this case, you will get exactly one allocation for your `Conn`, and it will manipulate only with small frames. If no, then additional allocations must be done in a runtime or an error must be returned. I said that this is weird for *general purpose* library, because in cases with payload of frames larger than 125 bytes (which is very likely to be) your const-sized Reader will do much more `read()` syscalls than one configured in a runtime of app-space (like `bufio.NewReaderSize`). For particular application thats looks fine to do if you know that any frame fits your const-sized reader buffer.

My question is – why you optimizing the part of upgrading to websocket? I mean, there is a lot of things happen when you accepting a new client connection – probably, the most expensive is ssl handshake, then, as in your example – read of http request (with lots of allocations), and then, eventually, allocation of your `Conn` structure. Against this ssl and http handshakes two separate allocations instead of one is not obviously a problem of efficiency. But what is actually could be a problem – is that how much memory and resources your millions of connections are consume – and thats why in that article and here in thread I am talking about memory reuse. I mean, your connections is not so short-lived I guess (in other way why use websockets?), thus upgrading is just a tiny part of their life cycle. When some connections become idle and you may not want to waste memory for their buffers – thats why Im suggesting to use epoll and buffer pools. Finally, even without epoll, your connections become closed, and you could reuse their buffers for newly coming connections. With such action, your app finnally will allocate as much memory as needed for your load (connections and their I/O frequency) needs and no more (probably) allocations will happen for upcoming connections.

**Comment by pascaldekloe** [comment]
@gobwas, it is not only the memory allocation and garbage collection costs that come with buffered I/O. You also do an additional data copy [write + read]. Hardware caches run useless that way, especially with the concurrency you describe in the article. Nice read b.t.w..

Unfortunately I can not elaborate on my use-cases due to confidentiality contract obligations. Sorry about that. However, the clutter of this extreme low-level library only makes sense for extreme performance needs. This is also how its use is advertised. I'm afraid it won't perform well due to the extra write. We can argue with theory, yet all I propose is a proof-in-the-pudding benchmark covering the whole process. Connection establishment is definitely relevant here indeed.

@cristaloleg, the link above leads to the benchmark.

**Comment by gobwas** [comment]
Sorry, are you really rely on CPU caches in network processing routine? How much time do you save on that against single `read()` syscall?

Again. If you implement your custom reader it is not a problem to avoid that copyings you pointed:

```go
buf := make([]byte, 131)
r := bytes.NewReader(buf[:6]) // 6 is your header size.
for {
    n, err := io.ReadFull(conn, buf)
    if err != nil {
        // handle error
    }
    h, err := ws.ReadHeader(r)
    if err != nil {
        // handle error
    }
    data := buf[6:6+h.Length]
    process(data)
}
```

And, finally, what do you want from me as an owner of this library with this issue and your app-specific cutset of WebSocket implementation?
