### ISSUE TITLE
Does this lib support concurrent write to websocket connection?

### ISSUE THREAD

**Issue by vklonghml** [gobwas/ws#69]
as the title said.

**Comment by ligser** [comment]
I'm not an author of the lib but have some experience with it.

Short answer:
No, it's not, you should handle concurrent writes by yourself.

Long answer:
If you use low-level API — you use the `net.Conn` as it is, and all buffering and concurrent writes should be handled in your code.
If you use the `wsutil.Writer`, you can [see](https://github.com/gobwas/ws/blob/master/wsutil/writer.go#L260) that its `Write` method does not have any mutex or something like that to prevent concurrent writes.
I think this lib is not intended to do that kind of work because it cannot be sure that outside code does not break all the things by call write on raw `net.Conn`. Because of this — «thread-safe» API here might cause false expectations. Also, I guess the author trying to keep the lib simple and fast but the synchronization is slow and complicated.

**Comment by gobwas** [comment]
@vklonghml this library does not deal with concurrency at all.

@ligser is absolutely correct saying:
> all buffering and concurrent writes should be handled in your code.

This lib is designed to be as simple as possible, and concurrency synchronization is not its area of responsibility. Thanks, @ligser.
